# Generated by Django 5.1.3 on 2024-11-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='frames/')),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='VideoFrame',
        ),
    ]
